<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\K3d.MyOrg.Application.Interface\K3d.MyOrg.Application.Interface.csproj" />
    <ProjectReference Include="..\K3d.MyOrg.Application\K3d.MyOrg.Application.csproj" />
    <ProjectReference Include="..\K3d.MyOrg.Core\K3d.MyOrg.Core.csproj" />
    <ProjectReference Include="..\K3d.MyOrg.DataAccess.Interface\K3d.MyOrg.DataAccess.Interface.csproj" />
    <ProjectReference Include="..\K3d.MyOrg.DataAccess\K3d.MyOrg.DataAccess.csproj" />
    <ProjectReference Include="..\K3d.MyOrg.Domain\K3d.MyOrg.Domain.csproj" />
  </ItemGroup>

</Project>