<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\K3d.MyOrg.Application.Interface\K3d.MyOrg.Application.Interface.csproj" />
    <ProjectReference Include="..\K3d.MyOrg.Core\K3d.MyOrg.Core.csproj" />
    <ProjectReference Include="..\K3d.MyOrg.DataAccess.Interface\K3d.MyOrg.DataAccess.Interface.csproj" />
    <ProjectReference Include="..\K3d.MyOrg.Domain\K3d.MyOrg.Domain.csproj" />
  </ItemGroup>

</Project>
